# https://docs.neoforged.net/docs/gettingstarted/modfiles

modLoader = "lowcodefml"
loaderVersion = "[1,)" # https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html

license = "AGPL-3.0"
issueTrackerURL = "https://github.com/"
# showAsDataPack = false
# showAsResourcePack = false

[[mods]]
modId = "mangocompatdelight"
version = "0.1.0"
displayName = "Compat Delight"
description = """Compat other mods with Farmer's Delight!"""
logoFile = "pack.png"
# updateJSONURL = ""
# credits = ""
authors = "EvanHsieh0415"
# displayURL = "https://github.com/"

[[dependencies.mod_id]]
modId = "minecraft"
# type = "required" # required, optional, discouraged or incompatible. default is required
# reason = ""
versionRange = "1.21.1" # https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
# ordering = "NONE" # NONE, AFTER, BEFORE. default is NONE
# side = "BOTH" # BOTH, CLIENT, SERVER. default is BOTH